### ISSUE TITLE
Chart scaling needs to be adjusted

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe-fba#26]
![image](https://user-images.githubusercontent.com/178003/72504788-6d380a00-3836-11ea-9cdf-ad398dc8bd42.png)

Move the highest class out of the chart and place it in a highlight box above the chart e.g.:

Residential Buildings 25 unflooded, 2000 flooded!

And then display the rest of the classes under the chart

**Comment by ann26** [comment]
hi @carina1000 could you give your opinion about the chart in the dashboard in http://staging.fbf.kartoza.com/ so that we can separate the residential buildings values from the rest of the building types from the chart? basically we want to move out the residential (the one with the very high number) from the chart

**Comment by carina1000** [comment]
Two solutions for this.
1. Change the 'out of' number to reflect higher at the residential:
![Screenshot 2020-01-17 at 09 58 29](https://user-images.githubusercontent.com/35214829/72594492-1dc60c80-3910-11ea-902a-23f9d46fec80.png)

Otherwise,

2. Separate the chart as follows:
![Screenshot 2020-01-17 at 10 19 52](https://user-images.githubusercontent.com/35214829/72595786-4996c180-3913-11ea-9ed7-f5f5e8ea8c51.png)
